-- 코드를 입력하세요
-- 세단 / suv중 2022년 11월 대여 가능, 30일간 50~200만 자동차 리스트

SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM 
-- 대여 가능한 차량을 먼저 구함 (HISTORY를 통해서)

-- 그 차량의 한달간의 비용을 계산함
CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;